services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wedding-app
    restart: unless-stopped
    volumes:
      - db_data:/data
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DB_PATH=/data/data.db
    networks:
      - web

volumes:
  db_data:
    driver: local

networks:
  web:
    external: true
